### ISSUE TITLE
Span method should not be match cased

### ISSUE THREAD

**Issue by HosseinArabbeigi** [neworld/spanner#18]
Hello There!
Thanks for amazing library! very helpful 👍 

I have a problem with span method, its shouldn't be match cased, for example when i want to bold **apple** it should bold all cases of **apple**, like Apple, APPLE, AppLe, aPPLLE, ...

Thanks.

**Comment by neworld** [comment]
Good idea! It could be easily solved with the flag `ignoreCase`.

**Comment by HosseinArabbeigi** [comment]
Nice, i will be free in next 15 days and add this feature.

**Comment by neworld** [comment]
No worries. I just added it to the 1.2.0 version. Keep in mind, this update was not idiomatic kotlin, because this library was created a long time ago for kotlinless environments. You could need some magic depending on the used kotlin version (you probably use):
```
.span("bar", ignoreCase = true, spans = *arrayOf(bold()))
```
I am planning to rewrite using kotlin as a first-class citizen in 2.0 version, which will have a more pleasant API.

**Comment by HosseinArabbeigi** [comment]
Thanks a lot @neworld, such a fast you are! :)
And about version two that's great news!

**Comment by aiKrice** [comment]
@neworld , if you need i like to review and or help you to rewrite to kotlin :)
Feel free to reach me :)
