### ISSUE TITLE
Vector image not being showned

### ISSUE THREAD

**Issue by jrcacd** [neworld/spanner#8]
Kotlin:
```
val texto = Spanner()
texto.append("", image(context.getResources().getDrawable(R.drawable.ic_star_on)))
```

Am I doing something wrong?

**Comment by neworld** [comment]
You are applying drawable on `""` A.K.A nothing. It should be at least `" "` (space). The same, as if you are using SpannableStringBuilder. I will think what could be done here. Maybe, do you have any idea?

**Comment by neworld** [comment]
Added less ambiguity method for appending images. Should following code work:
```
Spanner().append(image(context.getResources().getDrawable(R.drawable.ic_star_on)))
```

**Comment by jrcacd** [comment]
Still doesn't show the image.
```
val spanner = Spanner()
spanner.append(image(context.getResources().getDrawable(R.drawable.ic_star_on)))
title.text = spanner  //TextView
```

**Comment by neworld** [comment]
I will check vector case.

**Comment by neworld** [comment]
I spent some time to investigate until I realized probably bounds of the image are wrong. This library is a simple wrapper for `SpannableStringBuilder` and inherits all weakness from it. Working solution is [in the sample](https://github.com/neworld/spanner/blob/master/sample/src/main/java/lt/neworld/spanner/sample/SampleJavaActivity.java#L43-L44). I am not sure, this lib should change bounds because sometimes you want use specified size. Since you are using kotlin, you could write extension functions which helps to you.

**Comment by neworld** [comment]
I added another span creator. Following code should work:
```
val texto = Spanner()
texto.append(image(context, R.drawable.ic_star_on))
```

If you are supporting older than 21, you may need to enable vector support from resources:
```
AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
```

**Comment by jrcacd** [comment]
It's working. Thanks,

**Comment by jrcacd** [comment]
A question: How do I set the image tint?

**Comment by neworld** [comment]
You should use old solution but define bounds. I could create something like `imageIntrinsicBounds()`. What do you think?
